//  http://film.mtime.com/search/movies/movies?q=%E7%88%B1&suggestType=0

var movies = [
  {
    movieId: 144764,
    name: "爱",
    nameEn: "Love",
    movieType: "爱情 / 剧情",
    movieContentType: "电影",
    img: "http://img5.mtime.cn/mt/2020/09/30/215937.51171417_o.jpg",
    titleOthersCn: ["愛LOVE", "爱love", "Ai", "러브"],
    rating: 7,
    directors: ["钮承泽"],
    actors: ["舒淇", "赵薇"],
    directorObjs: [
      {
        id: 992990,
        name: "钮承泽",
      },
    ],
    actorObjs: [
      {
        id: 924551,
        name: "舒淇",
      },
      {
        id: 923349,
        name: "赵薇",
      },
    ],
    href: "http://movie.mtime.com/144764",
    canPlay: 1,
    locationName: "中国台湾",
    realTime: "2012年2月13日",
    year: 2012,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 120,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国台湾",
    rYear: 2012,
    rMonth: 2,
    rDay: 13,
  },
  {
    movieId: 148580,
    name: "爱",
    nameEn: "Amour",
    movieType: "剧情 / 爱情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2012/05/30/060816.72693707_o.jpg",
    titleOthersCn: [
      "爱·慕",
      "他们俩",
      "爱情",
      "Love",
      "Liebe",
      "Milosc",
      "Szerelem",
      "아무르",
      "Любов",
      "Agapi",
      "Amor",
      "Ljubezen",
      "Ljubov",
      "Ljubav",
      "Αγάπη",
      "Любовь",
      "Ahava",
      "Ask",
      "Rakkaus",
      "愛、アムール",
      "Liebe",
      "Armastus",
      "Amor",
      "Ai, Amûru",
      "Amor",
      "Ljubav",
      "Любов",
      "Amour",
      "Amor",
      "Amour",
      "Iubire",
      "Amour",
      "Amour",
      "Amour",
    ],
    rating: 8.1,
    directors: ["迈克尔·哈内克"],
    actors: ["埃玛妞·丽娃", "让·路易·特兰蒂尼昂"],
    directorObjs: [
      {
        id: 901504,
        name: "迈克尔·哈内克",
      },
    ],
    actorObjs: [
      {
        id: 924736,
        name: "埃玛妞·丽娃",
      },
      {
        id: 924635,
        name: "让·路易·特兰蒂尼昂",
      },
    ],
    href: "http://movie.mtime.com/148580",
    canPlay: 1,
    locationName: "奥地利",
    realTime: "2012年9月21日",
    year: 2012,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 127,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "奥地利",
    rYear: 2012,
    rMonth: 9,
    rDay: 21,
  },
  {
    movieId: 107438,
    name: "最爱",
    nameEn: "Love For Life",
    movieType: "剧情 / 爱情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2016/08/27/210452.65793562_o.jpg",
    titleOthersCn: [
      "魔术外传",
      "罪爱",
      "魔术时代",
      "Till Death Do Us Part",
      "Life Is A Miracle",
      "Mo Shu Shi Dai",
      "Mo shu shi dai",
      "Zui Ai",
      "L'amour éternel",
      "Love for Life",
      "Life Is a Miracle",
      "Love for Life",
      "Love for Live",
      "Til Death Do Us Part",
      "Mo shu wai zhuan",
    ],
    rating: 7.2,
    directors: ["顾长卫"],
    actors: ["章子怡", "郭富城"],
    directorObjs: [
      {
        id: 1123706,
        name: "顾长卫",
      },
    ],
    actorObjs: [
      {
        id: 912939,
        name: "章子怡",
      },
      {
        id: 928694,
        name: "郭富城",
      },
    ],
    href: "http://movie.mtime.com/107438",
    canPlay: 1,
    locationName: "中国",
    realTime: "2011年5月10日",
    year: 2011,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 105,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2011,
    rMonth: 5,
    rDay: 10,
  },
  {
    movieId: 12609,
    name: "真爱至上",
    nameEn: "Love Actually",
    movieType: "喜剧 / 剧情 / 爱情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2013/11/15/095856.10553263_o.jpg",
    titleOthersCn: [
      "爱是您，爱是我",
      "真的恋爱了",
      "真情角落",
      "Love Actually Is All Around",
      "Untitled Richard Curtis Project",
      "Realmente amor",
      "Tatsächlich... Liebe",
      "Agapi einai...",
      "Ahava Ze Kol Ha-Sippur",
      "Armastus on see...",
      "Ask her yerde",
      "Igazából szerelem",
      "O Amor Acontece",
      "Réellement l'amour",
      "Rakkautta vain",
      "Simplesmente Amor",
      "To wlasnie milosc",
      "U stvari ljubav",
      "러브 액츄얼리",
      "Наистина любов",
      "Láska nebeská",
      "Tatsächlich... Liebe",
      "Love Actually",
      "Αγάπη είναι...",
      "Zapravo ljubav",
      "Love Actually - L'amore davvero",
      "Love Actually",
      "Tegyvuoja meile",
      "Realmente amor",
      "Realmente amor",
      "Реальная любовь",
      "Pravzaprav ljubezen",
      "Реальне кохання",
      "Love Actually Is All Around",
      "Love Actually",
      "Pur si simplu dragoste",
      "Love Actually",
      "Love Actually",
    ],
    rating: 8.2,
    directors: ["理查德·柯蒂斯"],
    actors: ["休·格兰特", "比尔·奈伊"],
    directorObjs: [
      {
        id: 900503,
        name: "理查德·柯蒂斯",
      },
    ],
    actorObjs: [
      {
        id: 930566,
        name: "休·格兰特",
      },
      {
        id: 912575,
        name: "比尔·奈伊",
      },
    ],
    href: "http://movie.mtime.com/12609",
    canPlay: 1,
    locationName: "英国",
    realTime: "2003年11月21日",
    year: 2003,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 135,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "英国",
    rYear: 2003,
    rMonth: 11,
    rDay: 21,
  },
  {
    movieId: 83234,
    name: "简·爱",
    nameEn: "Jane Eyre",
    movieType: "剧情 / 爱情",
    movieContentType: "电影",
    img: "http://img21.mtime.cn/mt/2010/11/09/092428.45320351_o.jpg",
    titleOthersCn: ["简爱", "Jana Eyrova"],
    rating: 7.6,
    directors: ["凯瑞·福永"],
    actors: ["米娅·华希科沃斯卡", "迈克尔·法斯宾德"],
    directorObjs: [
      {
        id: 1478907,
        name: "凯瑞·福永",
      },
    ],
    actorObjs: [
      {
        id: 1271305,
        name: "米娅·华希科沃斯卡",
      },
      {
        id: 959054,
        name: "迈克尔·法斯宾德",
      },
    ],
    href: "http://movie.mtime.com/83234",
    canPlay: 1,
    locationName: "英国",
    realTime: "2011年3月11日",
    year: 2011,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 0,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "英国",
    rYear: 2011,
    rMonth: 3,
    rDay: 11,
  },
  {
    movieId: 181102,
    name: "爱神",
    nameEn: "Fall In Love",
    movieType: "爱情 / 剧情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2013/03/06/085354.69908087_o.jpg",
    titleOthersCn: ["爱神来了", "Ai Shen Lai Le"],
    rating: 7,
    directors: ["花明"],
    actors: ["钟汉良", "王子文"],
    directorObjs: [
      {
        id: 1970456,
        name: "花明",
      },
    ],
    actorObjs: [
      {
        id: 1088345,
        name: "钟汉良",
      },
      {
        id: 1282981,
        name: "王子文",
      },
    ],
    href: "http://movie.mtime.com/181102",
    canPlay: 1,
    locationName: "中国",
    realTime: "2013年3月8日",
    year: 2013,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 98,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2013,
    rMonth: 3,
    rDay: 8,
  },
  {
    movieId: 71012,
    name: "爱有来生",
    nameEn: "Eternal Beloved",
    movieType: "爱情 / 剧情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2014/02/23/052155.88600325_o.jpg",
    titleOthersCn: ["银杏，银杏", "Yin Xing,Yin Xing", "Ai you lai sheng"],
    rating: 7.3,
    directors: ["俞飞鸿"],
    actors: ["段奕宏", "俞飞鸿"],
    directorObjs: [
      {
        id: 962145,
        name: "俞飞鸿",
      },
    ],
    actorObjs: [
      {
        id: 1269810,
        name: "段奕宏",
      },
      {
        id: 962145,
        name: "俞飞鸿",
      },
    ],
    href: "http://movie.mtime.com/71012",
    canPlay: 1,
    locationName: "中国",
    realTime: "2009年9月3日",
    year: 2009,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 92,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2009,
    rMonth: 9,
    rDay: 3,
  },
  {
    movieId: 140250,
    name: "想爱就爱",
    nameEn: "Yes or No",
    movieType: "爱情 / 喜剧",
    movieContentType: "电影",
    img: "http://img21.mtime.cn/mt/2010/11/29/182643.61038904_o.jpg",
    titleOthersCn: [
      "拉小手",
      "是否敢爱",
      "อยากรักก็รักเลย",
      "Yes or No: Yaak Rak Gaw Rak Loey",
    ],
    rating: 7.7,
    directors: ["萨拉萨瓦蒂·翁索姆佩奇"],
    actors: ["阿丽莎拉·唐伯里苏斯", "索兰娜特·尤潘农"],
    directorObjs: [
      {
        id: 1805494,
        name: "萨拉萨瓦蒂·翁索姆佩奇",
      },
    ],
    actorObjs: [
      {
        id: 1805495,
        name: "阿丽莎拉·唐伯里苏斯",
      },
      {
        id: 1805496,
        name: "索兰娜特·尤潘农",
      },
    ],
    href: "http://movie.mtime.com/140250",
    canPlay: 0,
    locationName: "泰国",
    realTime: "2010年12月16日",
    year: 2010,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 0,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "泰国",
    rYear: 2010,
    rMonth: 12,
    rDay: 16,
  },
  {
    movieId: 174731,
    name: "天台爱情",
    nameEn: "The Rooftop",
    movieType: "爱情 / 歌舞 / 喜剧",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2013/07/02/091435.24863431_o.jpg",
    titleOthersCn: ["天台", "Tian Tai"],
    rating: 7.2,
    directors: ["周杰伦"],
    actors: ["周杰伦", "李心艾"],
    directorObjs: [
      {
        id: 943799,
        name: "周杰伦",
      },
    ],
    actorObjs: [
      {
        id: 943799,
        name: "周杰伦",
      },
      {
        id: 2044189,
        name: "李心艾",
      },
    ],
    href: "http://movie.mtime.com/174731",
    canPlay: 1,
    locationName: "中国台湾",
    realTime: "2013年7月11日",
    year: 2013,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 117,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国台湾",
    rYear: 2013,
    rMonth: 7,
    rDay: 11,
  },
  {
    movieId: 126408,
    name: "爱出色",
    nameEn: "Color Me Love",
    movieType: "喜剧 / 爱情",
    movieContentType: "电影",
    img: "http://img21.mtime.cn/mt/2010/11/12/102248.20228328_o.jpg",
    titleOthersCn: ["我的天空", "Ai Chu Se"],
    rating: 6.2,
    directors: ["陈奕利"],
    actors: ["姚晨", "刘烨"],
    directorObjs: [
      {
        id: 1256656,
        name: "陈奕利",
      },
    ],
    actorObjs: [
      {
        id: 1252497,
        name: "姚晨",
      },
      {
        id: 917288,
        name: "刘烨",
      },
    ],
    href: "http://movie.mtime.com/126408",
    canPlay: 0,
    locationName: "中国",
    realTime: "2010年11月9日",
    year: 2010,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 97,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2010,
    rMonth: 11,
    rDay: 9,
  },
  {
    movieId: 162309,
    name: "HOLD住爱",
    nameEn: "Holding Love",
    movieType: "爱情 / 悬疑 / 喜剧",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2016/09/08/153646.94408602_o.jpg",
    titleOthersCn: [],
    rating: 3,
    directors: ["张琦"],
    actors: ["杨幂", "刘恺威"],
    directorObjs: [
      {
        id: 1299407,
        name: "张琦",
      },
    ],
    actorObjs: [
      {
        id: 1249009,
        name: "杨幂",
      },
      {
        id: 939283,
        name: "刘恺威",
      },
    ],
    href: "http://movie.mtime.com/162309",
    canPlay: 1,
    locationName: "中国",
    realTime: "2012年8月23日",
    year: 2012,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 98,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2012,
    rMonth: 8,
    rDay: 23,
  },
  {
    movieId: 194542,
    name: "回到爱开始的地方",
    nameEn: "A Moment Of Love",
    movieType: "爱情 / 剧情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2013/08/16/141827.68194329_o.jpg",
    titleOthersCn: [
      "爱的季节",
      "Hui Dao Ai Kai Shi De Di Fang",
      "The Season Of Love",
      "Moments of Love",
    ],
    rating: 7.2,
    directors: ["林孝谦"],
    actors: ["周渝民", "刘诗诗"],
    directorObjs: [
      {
        id: 1646883,
        name: "林孝谦",
      },
    ],
    actorObjs: [
      {
        id: 1250272,
        name: "周渝民",
      },
      {
        id: 1273178,
        name: "刘诗诗",
      },
    ],
    href: "http://movie.mtime.com/194542",
    canPlay: 1,
    locationName: "中国",
    realTime: "2013年8月23日",
    year: 2013,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 90,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2013,
    rMonth: 8,
    rDay: 23,
  },
  {
    movieId: 83327,
    name: "爱丽丝梦游仙境",
    nameEn: "Alice in Wonderland",
    movieType: "冒险 / 家庭 / 奇幻",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2014/02/23/061233.17430039_o.jpg",
    titleOthersCn: [
      "魔境梦游",
      "爱丽丝梦游奇境",
      "爱丽丝漫游奇境",
      "Alice",
      "Alice no País das Maravilhas",
      "Alice au pays des merveilles",
      "Alice i Underlandet",
      "Alicia en el país de las maravillas",
      "I Aliki sti hora ton thavmaton",
      "Aliza Be Eretz Ha Pla'ot",
      "Alice Csodaországban",
      "Alice i Eventyrland",
      "Alice i eventyrland",
      "Alice im Wunderland",
      "Alice imedemaal",
      "Alice in Wonderland: An IMAX 3D Experience",
      "Alica v krajine zázrakov",
      "Alice Csodaországban IMAX 3D",
      "Alisa saotsrebata kvekanashi",
      "Алиса в страната на чудесата",
      "Alice im Wunderland",
      "Alicia en el país de las maravillas",
      "Η Αλίκη στη χώρα των θαυμάτων",
      "Alisa u zemlji čudesa",
      "Alisa stebuklu salyje",
      "Alicia en el país de las maravillas",
      "Alicia en el país de las maravillas",
      "Alicja w Krainie Czarów",
      "Alice no País das Maravilhas",
      "Alisa u zemlji čuda",
      "Алиса в Стране чудес",
      "Alica v cudezni dezeli",
      "Alice in Wonderland",
      "Alenka v říši divů",
      "Alicia en el País de las Maravillas",
      "Liisa Ihmemaassa",
      "Alice i Eventyrland",
      "Alice în Tara Minunilor",
      "Alice i Underlandet",
      "Alice au pays des merveilles",
      "Alice ar tir na n-iontas",
      "Alice in Wonderland",
      "Alice in Wonderland",
      "アリス・イン・ワンダーランド",
      "Alise Brīnumzemē",
      "魔境夢遊",
      "Alice harikalar diyarında",
      "Аліса в країні чудес",
      "Alice in Wonderland",
      "Alice Ở Xứ Sở Thần Tiên",
    ],
    rating: 7.4,
    directors: ["蒂姆·波顿"],
    actors: ["米娅·华希科沃斯卡", "约翰尼·德普"],
    directorObjs: [
      {
        id: 892796,
        name: "蒂姆·波顿",
      },
    ],
    actorObjs: [
      {
        id: 1271305,
        name: "米娅·华希科沃斯卡",
      },
      {
        id: 893397,
        name: "约翰尼·德普",
      },
    ],
    href: "http://movie.mtime.com/83327",
    canPlay: 1,
    locationName: "美国",
    realTime: "2010年3月26日",
    year: 2010,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 108,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "美国",
    rYear: 2010,
    rMonth: 3,
    rDay: 26,
  },
  {
    movieId: 11970,
    name: "天使爱美丽",
    nameEn: "Amelie",
    movieType: "喜剧 / 爱情",
    movieContentType: "电影",
    img: "http://img21.mtime.cn/mt/2012/02/14/111655.86253293_o.jpg",
    titleOthersCn: [
      "天使艾米莉",
      "艾蜜莉的异想世界",
      "艾蜜丽",
      "阿梅丽的奇妙命运",
      "天使艾美丽",
      "Amélie",
      "Amélie des Abbesses",
      "아멜리에",
      "Amelie",
      "Невероятната съдба на Амели Пулен",
      "O Fabuloso Destino de Amélie Poulain",
      "Amélie",
      "Amélie",
      "El fabuloso destino de Amelie Poulain",
      "Amélie z Montmartru",
      "Die fabelhafte Welt der Amelie",
      "Den fabelagtige Amélie fra Montmartre",
      "Amelie",
      "Amélie",
      "Amélie",
      "Amélie",
      "Amelie",
      "Amelie",
      "Amelie",
      "Amélie csodálatos élete",
      "Il favoloso mondo di Amélie",
      "Ameri",
      "Amelie",
      "Den fabelaktige Amélie fra Montmartre",
      "Amélie",
      "Amelia",
      "O Fabuloso Destino de Amélie",
      "Amélie",
      "Čudesna sudbina Amelije Pulen",
      "Амели",
      "Amelie från Montmartre",
      "Amélie",
      "Amélie",
      "Le fabuleux destin d'Amélie Poulain",
      "Le fabuleux destin d'Amélie Poulain",
      "Le fabuleux destin d'Amélie Poulain",
      "Αμελί",
      "Amelija iš Monmartro",
      "Amélia",
      "Неймовiрна доля Амелi Пулен",
      "Amélie",
      "Amélie",
      "Amélie",
      "Amélie",
    ],
    rating: 8.4,
    directors: ["让-皮埃尔·热内"],
    actors: ["奥黛丽·塔图", "马修·卡索维茨"],
    directorObjs: [
      {
        id: 899844,
        name: "让-皮埃尔·热内",
      },
    ],
    actorObjs: [
      {
        id: 912600,
        name: "奥黛丽·塔图",
      },
      {
        id: 900987,
        name: "马修·卡索维茨",
      },
    ],
    href: "http://movie.mtime.com/11970",
    canPlay: 1,
    locationName: "法国",
    realTime: "2001年4月25日",
    year: 2001,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 122,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "法国",
    rYear: 2001,
    rMonth: 4,
    rDay: 25,
  },
  {
    movieId: 56814,
    name: "可爱的骨头",
    nameEn: "The Lovely Bones",
    movieType: "剧情 / 奇幻 / 惊悚",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2014/02/23/042504.75055029_o.jpg",
    titleOthersCn: [
      "尸中罪",
      "可爱的尸骨",
      "亲切的骨头",
      "苏西的世界",
      "Amabili resti",
      "Desde mi cielo",
      "In meinem Himmel",
      "Cennetimden Bakarken",
      "Lovely Bone",
      "Pevné pouto",
      "V mojih nebesih",
      "Очи от рая",
      "Um Olhar do Paraíso",
      "La nostalgie de l'ange",
      "Her fra min himmel",
      "Minu armsad luud",
      "The Lovely Bones",
      "Oma taivas",
      "Lovely Bones",
      "Paradeisenia osta",
      "Παραδεισένια Οστά",
      "Ljupke kosti",
      "Komfortos mennyország",
      "Mabat mi'Gan Eden",
      "Behesht e Man",
      "Desde mi cielo",
      "Alle mine kjære",
      "Desde mi cielo",
      "Nostalgia aniola",
      "Visto do Céu",
      "Din raiul meu",
      "Divne kosti",
      "Милые кости",
      "Flickan från ovan",
      "Милi костi",
      "The Lovely Bones",
    ],
    rating: 7.4,
    directors: ["彼得·杰克逊"],
    actors: ["西尔莎·罗南", "马克·沃尔伯格"],
    directorObjs: [
      {
        id: 892783,
        name: "彼得·杰克逊",
      },
    ],
    actorObjs: [
      {
        id: 1269915,
        name: "西尔莎·罗南",
      },
      {
        id: 952424,
        name: "马克·沃尔伯格",
      },
    ],
    href: "http://movie.mtime.com/56814",
    canPlay: 1,
    locationName: "美国",
    realTime: "2009年12月26日",
    year: 2009,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 135,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "美国",
    rYear: 2009,
    rMonth: 12,
    rDay: 26,
  },
  {
    movieId: 125326,
    name: "恋爱通告",
    nameEn: "Love In Disguise",
    movieType: "爱情 / 喜剧",
    movieContentType: "电影",
    img: "http://img21.mtime.cn/mt/2010/07/19/110121.60184611_o.jpg",
    titleOthersCn: [
      "玩转大明星",
      "Love Announcement",
      "Lian Ai Tong Gao",
      "Wan Zhuan Da Ming Xing",
    ],
    rating: 6.3,
    directors: ["王力宏"],
    actors: ["王力宏", "刘亦菲"],
    directorObjs: [
      {
        id: 942612,
        name: "王力宏",
      },
    ],
    actorObjs: [
      {
        id: 942612,
        name: "王力宏",
      },
      {
        id: 1176638,
        name: "刘亦菲",
      },
    ],
    href: "http://movie.mtime.com/125326",
    canPlay: 1,
    locationName: "中国",
    realTime: "2010年8月12日",
    year: 2010,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 99,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2010,
    rMonth: 8,
    rDay: 12,
  },
  {
    movieId: 223848,
    name: "爱宠大机密",
    nameEn: "The Secret Life of Pets",
    movieType: "动画 / 冒险 / 喜剧",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2016/06/21/093148.32874907_o.jpg",
    titleOthersCn: [
      "宠物当家",
      "Pet Pet当家",
      "宠物的秘密生活",
      "Untitled Pets Movie",
      "La vida secreta de tus mascotas",
      "Сами вкъщи",
      "Pets: A Vida Secreta dos Bichos",
      "La vida secreta de tus mascotas",
      "Pets",
      "Lemmikkien salainen elämä",
      "Comme des bêtes",
      "A kis kedvencek titkos élete",
      "Pets - Vita da animali",
      "Milulu Slepena Dzive",
      "A Vida Secreta dos Nossos Bichos",
      "Tajne avanture kućnih ljubimaca",
      "Тайная жизнь домашних животных",
      "Husdjurens hemliga liv",
      "Kæledyrenes hemmelige liv",
      "Slaptas augintiniu gyvenimas",
      "Μπάτε σκύλοι αλέστε",
      "Ha'kha'yim ha'sodiyim shel kha'yot ha'makhmad",
      "Kjæledyrenes hemmelige liv",
      "Jeta sekrete e kafshëve",
      "Huisdiergeheimen",
      "Comme des bêtes",
      "Mascotas",
      "Comme des bêtes",
      "Tajni život ljubimaca",
      "La vida secreta de tus mascotas",
      "Huisdiergeheimen",
      "Skrivno življenje hišnih ljubljenčkov",
      "The Secret Life of Pets",
      "Mascotes",
      "La vida secreta de tus mascotas",
      "Sekretne życie zwierzaków domowych",
      "Evcil Hayvanlarin Gizli Yasami",
      "La vida secreta de tus mascotas",
      "Singuri acasã",
      "Tajný život maznáčikov",
      "Секрети домашнiх тварин",
      "Tajný život mazlíčků",
      "Bate Skili Aleste",
      "The Secret Life of Pets",
      "Dang Cap Thu Cung",
    ],
    rating: 7.8,
    directors: ["亚罗·切尼", "克里斯·雷纳德"],
    actors: ["何炅", "陈佩斯"],
    directorObjs: [
      {
        id: 1322328,
        name: "亚罗·切尼",
      },
      {
        id: 1269972,
        name: "克里斯·雷纳德",
      },
    ],
    actorObjs: [
      {
        id: 1249007,
        name: "何炅",
      },
      {
        id: 985029,
        name: "陈佩斯",
      },
    ],
    href: "http://movie.mtime.com/223848",
    canPlay: 1,
    locationName: "美国",
    realTime: "2016年8月2日",
    year: 2016,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 86,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "美国",
    rYear: 2016,
    rMonth: 8,
    rDay: 2,
  },
  {
    movieId: 219784,
    name: "爱乐之城",
    nameEn: "La La Land",
    movieType: "喜剧 / 剧情 / 音乐",
    movieContentType: "电影",
    img: "http://img5.mtime.cn/mt/2017/02/08/093237.40835159_o.jpg",
    titleOthersCn: [
      "啦啦之地",
      "星声梦里人",
      "乐来越爱你",
      "Kaliforniai álom",
      "La La Land: Cantando Estações",
      "La La Land: Ciudad de Sueños",
      "Kalifornijos svajos",
      "La La Land: Melodia de Amor",
      "Ла-Ла Ленд",
      "Asiklar Sehri",
      "La La Land: Una historia de amor",
      "Pour l'amour d'Hollywood",
      "La La Land: Ciudad de Sueños",
      "La La Land: California unistused",
      "La La Land: una historia de amor",
      "La La Land: Una historia de amor",
      "Dežela La la",
      "LaLa Land",
      "Nhung Ke Kho Mong Mo",
      "La La Land: Una Historia de Amor",
      "Ai Yue Zhi Cheng",
      "La La Land: Ciudad de Sueños",
      "La La Land: Ciudad de Sueños",
      "La La Land: Una Historia de Amor",
      "La La Land",
      "La La Land: Ciudad de Sueños",
      "La La Land",
      "La La Land",
      "La La Land",
      "La La Land: Ciudad de Sueños",
      "La La Land: Ciudad de Sueños",
      "La La Land",
      "La La Land: Ciudad de Sueños",
      "Ла-Ла Ленд",
      "La La Land: Ciudad de Sueños",
      "La La Land",
      "La ciudad de las estrellas (La La Land)",
      "La La Land",
      "La La Land",
      "La La Land",
      "La La Land",
      "Orasul stelelor",
      "La La Land",
    ],
    rating: 8,
    directors: ["达米恩·查泽雷"],
    actors: ["瑞恩·高斯林", "艾玛·斯通"],
    directorObjs: [
      {
        id: 1610650,
        name: "达米恩·查泽雷",
      },
    ],
    actorObjs: [
      {
        id: 915080,
        name: "瑞恩·高斯林",
      },
      {
        id: 1301063,
        name: "艾玛·斯通",
      },
    ],
    href: "http://movie.mtime.com/219784",
    canPlay: 1,
    locationName: "美国",
    realTime: "2017年2月14日",
    year: 2016,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 129,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "美国",
    rYear: 2017,
    rMonth: 2,
    rDay: 14,
  },
  {
    movieId: 209381,
    name: "放手爱",
    nameEn: "Let go for love",
    movieType: "爱情 / 喜剧",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2014/04/18/183924.23603664_o.jpg",
    titleOthersCn: ["爱情博弈"],
    rating: 2.4,
    directors: ["张敏"],
    actors: ["蔡卓妍", "杜汶泽"],
    directorObjs: [
      {
        id: 893424,
        name: "张敏",
      },
    ],
    actorObjs: [
      {
        id: 923222,
        name: "蔡卓妍",
      },
      {
        id: 924886,
        name: "杜汶泽",
      },
    ],
    href: "http://movie.mtime.com/209381",
    canPlay: 1,
    locationName: "中国",
    realTime: "2014年4月30日",
    year: 2014,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 93,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2014,
    rMonth: 4,
    rDay: 30,
  },
  {
    movieId: 208284,
    name: "亲爱的",
    nameEn: "Dearest",
    movieType: "家庭 / 剧情",
    movieContentType: "电影",
    img: "http://img31.mtime.cn/mt/2016/09/02/173802.89916613_o.jpg",
    titleOthersCn: [
      "家",
      "打拐",
      "家之亲爱的小孩",
      "亲爱的小孩",
      "O Mais Querido",
      "Yakiri",
      "Saiai no ko",
      "Dearest",
    ],
    rating: 8.1,
    directors: ["陈可辛"],
    actors: ["赵薇", "黄渤"],
    directorObjs: [
      {
        id: 892817,
        name: "陈可辛",
      },
    ],
    actorObjs: [
      {
        id: 923349,
        name: "赵薇",
      },
      {
        id: 1249885,
        name: "黄渤",
      },
    ],
    href: "http://movie.mtime.com/208284",
    canPlay: 1,
    locationName: "中国",
    realTime: "2014年9月26日",
    year: 2014,
    releaseStatus: 0,
    isTicket: false,
    isFilter: false,
    isVideo: false,
    length: 130,
    saleType: 0,
    ticket: false,
    video: false,
    filter: false,
    rLocation: "中国",
    rYear: 2014,
    rMonth: 9,
    rDay: 26,
  },
];
