var data = {
    "code": 0,
    "data": {
        "pageIndex": 1,
        "pageSize": 2,
        "hasNext": true,
        "items": [
            {
                "id": 300773,
                "title": "本周热门Top10",
                "subTitle": "",
                "type": 1,
                "status": 2,
                "year": null,
                "description": "本周热门Top10",
                "coverImg": "",
                "modifyTime": "2023-03-06 14:00:00",
                "publishTime": 1678082400000,
                "enableComment": true,
                "enableCopyright": true,
                "editUserId": 0,
                "editUserName": null,
                "items": [
                    {
                        "id": 10022812,
                        "listId": 300773,
                        "ordinal": 1,
                        "rank": 1,
                        "itemId": "268448",
                        "itemType": 1,
                        "title": "断网/Disconnect'd(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/02/03/101006.81662021_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 268448,
                            "movieName": "断网",
                            "movieNameEn": "Disconnect'd",
                            "director": "黄庆勋",
                            "actors": "郭富城",
                            "releaseDate": "2023年3月3日",
                            "releaseLocation": "中国香港",
                            "score": "",
                            "img": "http://img5.mtime.cn/mt/2023/02/03/101006.81662021_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022813,
                        "listId": 300773,
                        "ordinal": 2,
                        "rank": 2,
                        "itemId": "273489",
                        "itemType": 1,
                        "title": "毒舌律师/A Guilty Conscience(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/01/18/171926.64175652_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 273489,
                            "movieName": "毒舌律师",
                            "movieNameEn": "A Guilty Conscience",
                            "director": "吴炜伦",
                            "actors": "黄子华",
                            "releaseDate": "2023年2月24日",
                            "releaseLocation": "中国香港",
                            "score": "",
                            "img": "http://img5.mtime.cn/mt/2023/01/18/171926.64175652_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022814,
                        "listId": 300773,
                        "ordinal": 3,
                        "rank": 3,
                        "itemId": "266249",
                        "itemType": 1,
                        "title": "蚁人与黄蜂女：量子狂潮/Ant-Man and the Wasp: Quantumania(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/01/17/204446.33342328_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 266249,
                            "movieName": "蚁人与黄蜂女：量子狂潮",
                            "movieNameEn": "Ant-Man and the Wasp: Quantumania",
                            "director": "佩顿·里德",
                            "actors": "凯瑟琳·纽顿",
                            "releaseDate": "2023年2月17日",
                            "releaseLocation": "美国",
                            "score": "6.7",
                            "img": "http://img5.mtime.cn/mt/2023/01/17/204446.33342328_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022815,
                        "listId": 300773,
                        "ordinal": 4,
                        "rank": 4,
                        "itemId": "269295",
                        "itemType": 1,
                        "title": "流浪地球2/The Wandering Earth Ⅱ(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/01/24/105642.29034476_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 269295,
                            "movieName": "流浪地球2",
                            "movieNameEn": "The Wandering Earth Ⅱ",
                            "director": "郭帆",
                            "actors": null,
                            "releaseDate": "2023年1月22日",
                            "releaseLocation": "中国",
                            "score": "8.4",
                            "img": "http://img5.mtime.cn/mt/2023/01/24/105642.29034476_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022816,
                        "listId": 300773,
                        "ordinal": 5,
                        "rank": 5,
                        "itemId": "270546",
                        "itemType": 1,
                        "title": "保你平安/Post Truth(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/02/17/115108.14733184_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 270546,
                            "movieName": "保你平安",
                            "movieNameEn": "Post Truth",
                            "director": "大鹏",
                            "actors": null,
                            "releaseDate": "2023年3月10日",
                            "releaseLocation": "中国",
                            "score": "",
                            "img": "http://img5.mtime.cn/mt/2023/02/17/115108.14733184_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022817,
                        "listId": 300773,
                        "ordinal": 6,
                        "rank": 6,
                        "itemId": "270662",
                        "itemType": 1,
                        "title": "回廊亭/Revival(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/02/15/093137.97742682_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 270662,
                            "movieName": "回廊亭",
                            "movieNameEn": "Revival",
                            "director": "来牧宽",
                            "actors": null,
                            "releaseDate": "2023年3月10日",
                            "releaseLocation": "中国",
                            "score": "",
                            "img": "http://img5.mtime.cn/mt/2023/02/15/093137.97742682_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022818,
                        "listId": 300773,
                        "ordinal": 7,
                        "rank": 7,
                        "itemId": "270479",
                        "itemType": 1,
                        "title": "无名/Hidden Blade(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/01/01/230110.43988306_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 270479,
                            "movieName": "无名",
                            "movieNameEn": "Hidden Blade",
                            "director": "程耳",
                            "actors": null,
                            "releaseDate": "2023年1月22日",
                            "releaseLocation": "中国",
                            "score": "7.3",
                            "img": "http://img5.mtime.cn/mt/2023/01/01/230110.43988306_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022819,
                        "listId": 300773,
                        "ordinal": 8,
                        "rank": 8,
                        "itemId": "271882",
                        "itemType": 1,
                        "title": "满江红/Full River Red(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2023/01/14/113221.72316232_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 271882,
                            "movieName": "满江红",
                            "movieNameEn": "Full River Red",
                            "director": "张艺谋",
                            "actors": "易烊千玺",
                            "releaseDate": "2023年1月22日",
                            "releaseLocation": "中国",
                            "score": "7.6",
                            "img": "http://img5.mtime.cn/mt/2023/01/14/113221.72316232_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022820,
                        "listId": 300773,
                        "ordinal": 9,
                        "rank": 9,
                        "itemId": "272697",
                        "itemType": 1,
                        "title": "千寻小姐/ちひろさん(2023)",
                        "coverImg": "http://img5.mtime.cn/mt/2022/12/06/172733.11339932_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 272697,
                            "movieName": "千寻小姐",
                            "movieNameEn": "ちひろさん",
                            "director": "今泉力哉",
                            "actors": null,
                            "releaseDate": "2023年2月23日",
                            "releaseLocation": "日本",
                            "score": "",
                            "img": "http://img5.mtime.cn/mt/2022/12/06/172733.11339932_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 10022821,
                        "listId": 300773,
                        "ordinal": 10,
                        "rank": 10,
                        "itemId": "128969",
                        "itemType": 1,
                        "title": "阿凡达：水之道/Avatar: The Way of Water(2022)",
                        "coverImg": "http://img5.mtime.cn/mt/2022/11/23/115505.87337432_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 128969,
                            "movieName": "阿凡达：水之道",
                            "movieNameEn": "Avatar: The Way of Water",
                            "director": "詹姆斯·卡梅隆",
                            "actors": "萨姆·沃辛顿",
                            "releaseDate": "2022年12月16日",
                            "releaseLocation": "美国",
                            "score": "8.1",
                            "img": "http://img5.mtime.cn/mt/2022/11/23/115505.87337432_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    }
                ],
                "itemsTotalCount": 10
            },
            {
                "id": 300518,
                "title": "25部电影中的坚强母亲",
                "subTitle": "",
                "type": 1,
                "status": 2,
                "year": null,
                "description": "在一年一度的母亲节，让我们看看电影里坚强的母亲吧！",
                "coverImg": "http://img5.mtime.cn/mg/2018/11/07/142715.81959932.jpg",
                "modifyTime": "2022-05-08 16:44:49",
                "publishTime": 1651999489000,
                "enableComment": true,
                "enableCopyright": false,
                "editUserId": 0,
                "editUserName": null,
                "items": [
                    {
                        "id": 14952,
                        "listId": 300518,
                        "ordinal": 1,
                        "rank": 1,
                        "itemId": "95823",
                        "itemType": 1,
                        "title": "天佑鲍比/Prayers for Bobby(2009)",
                        "coverImg": "http://img31.mtime.cn/mt/2016/06/15/151150.18036433_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 95823,
                            "movieName": "天佑鲍比",
                            "movieNameEn": "Prayers for Bobby",
                            "director": "拉塞尔·马尔卡希",
                            "actors": "西格妮·韦弗",
                            "releaseDate": "2009年1月24日",
                            "releaseLocation": "美国",
                            "score": "8.2",
                            "img": "http://img31.mtime.cn/mt/2016/06/15/151150.18036433_o.jpg",
                            "award": "迷你剧/电视电影最佳女主角",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14953,
                        "listId": 300518,
                        "ordinal": 2,
                        "rank": 2,
                        "itemId": "13825",
                        "itemType": 1,
                        "title": "神女/Goddess(1934)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/22/232530.37291092_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 13825,
                            "movieName": "神女",
                            "movieNameEn": "Goddess",
                            "director": "吴永刚",
                            "actors": "黎铿",
                            "releaseDate": "1934年0月0日",
                            "releaseLocation": "中国",
                            "score": "8.3",
                            "img": "http://img31.mtime.cn/mt/2014/02/22/232530.37291092_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14954,
                        "listId": 300518,
                        "ordinal": 3,
                        "rank": 3,
                        "itemId": "122493",
                        "itemType": 1,
                        "title": "告白/Confessions(2010)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/082621.99364976_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 122493,
                            "movieName": "告白",
                            "movieNameEn": "Confessions",
                            "director": "中岛哲也",
                            "actors": "松隆子",
                            "releaseDate": "2010年6月5日",
                            "releaseLocation": "日本",
                            "score": "8.2",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/082621.99364976_o.jpg",
                            "award": "最佳亚洲电影",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14955,
                        "listId": 300518,
                        "ordinal": 4,
                        "rank": 4,
                        "itemId": "56059",
                        "itemType": 1,
                        "title": "母亲/Kaabee(2008)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/042134.93309063_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 56059,
                            "movieName": "母亲",
                            "movieNameEn": "Kaabee",
                            "director": "山田洋次",
                            "actors": "吉永小百合",
                            "releaseDate": "2008年1月26日",
                            "releaseLocation": "日本",
                            "score": "8.0",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/042134.93309063_o.jpg",
                            "award": "金熊奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14956,
                        "listId": 300518,
                        "ordinal": 5,
                        "rank": 5,
                        "itemId": "102279",
                        "itemType": 1,
                        "title": "岁月神偷/Echoes Of The Rainbow(2010)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/071655.53863162_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 102279,
                            "movieName": "岁月神偷",
                            "movieNameEn": "Echoes Of The Rainbow",
                            "director": "罗启锐",
                            "actors": "吴君如",
                            "releaseDate": "2010年4月16日",
                            "releaseLocation": "中国香港",
                            "score": "8.0",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/071655.53863162_o.jpg",
                            "award": "儿童电影-最佳影片",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14957,
                        "listId": 300518,
                        "ordinal": 6,
                        "rank": 6,
                        "itemId": "78902",
                        "itemType": 1,
                        "title": "母亲/Mother(2009)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/055359.65950941_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 78902,
                            "movieName": "母亲",
                            "movieNameEn": "Mother",
                            "director": "奉俊昊",
                            "actors": "金惠子",
                            "releaseDate": "2009年5月28日",
                            "releaseLocation": "韩国",
                            "score": "7.9",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/055359.65950941_o.jpg",
                            "award": "最佳电影奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14958,
                        "listId": 300518,
                        "ordinal": 7,
                        "rank": 7,
                        "itemId": "12109",
                        "itemType": 1,
                        "title": "关于我母亲的一切/Todo sobre mi madre(1999)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/22/230320.75494657_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 12109,
                            "movieName": "关于我母亲的一切",
                            "movieNameEn": "Todo sobre mi madre",
                            "director": "佩德罗·阿莫多瓦",
                            "actors": "丝莉亚·洛芙",
                            "releaseDate": "1999年4月16日",
                            "releaseLocation": "西班牙",
                            "score": "8.0",
                            "img": "http://img31.mtime.cn/mt/2014/02/22/230320.75494657_o.jpg",
                            "award": "最佳外语片",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14959,
                        "listId": 300518,
                        "ordinal": 8,
                        "rank": 8,
                        "itemId": "10778",
                        "itemType": 1,
                        "title": "黑暗中的舞者/Dancer in the Dark(2000)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/22/224712.70533981_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 10778,
                            "movieName": "黑暗中的舞者",
                            "movieNameEn": "Dancer in the Dark",
                            "director": "拉斯·冯·提尔",
                            "actors": "比约克",
                            "releaseDate": "2000年9月8日",
                            "releaseLocation": "西班牙",
                            "score": "7.9",
                            "img": "http://img31.mtime.cn/mt/2014/02/22/224712.70533981_o.jpg",
                            "award": "最佳原创歌曲",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14960,
                        "listId": 300518,
                        "ordinal": 9,
                        "rank": 9,
                        "itemId": "197687",
                        "itemType": 1,
                        "title": "菲洛梅娜/Philomena(2013)",
                        "coverImg": "http://img31.mtime.cn/mt/2013/09/02/113656.92932803_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 197687,
                            "movieName": "菲洛梅娜",
                            "movieNameEn": "Philomena",
                            "director": "斯蒂芬·弗雷斯",
                            "actors": "朱迪·丹奇",
                            "releaseDate": "2013年11月1日",
                            "releaseLocation": "英国",
                            "score": "7.9",
                            "img": "http://img31.mtime.cn/mt/2013/09/02/113656.92932803_o.jpg",
                            "award": "金狮奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14961,
                        "listId": 300518,
                        "ordinal": 10,
                        "rank": 10,
                        "itemId": "18097",
                        "itemType": 1,
                        "title": "世界上最疼我的那个人去了/Gone Is the One Who Held Me Dearest in the World(2002)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/002515.54893293_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 18097,
                            "movieName": "世界上最疼我的那个人去了",
                            "movieNameEn": "Gone Is the One Who Held Me Dearest in the World",
                            "director": "马俪文",
                            "actors": "斯琴高娃",
                            "releaseDate": "2002年10月28日",
                            "releaseLocation": "中国",
                            "score": "8.1",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/002515.54893293_o.jpg",
                            "award": "亚洲电影奖-特别关注",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14962,
                        "listId": 300518,
                        "ordinal": 11,
                        "rank": 11,
                        "itemId": "46080",
                        "itemType": 1,
                        "title": "密阳/Secret Sunshine(2007)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/034007.94889821_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 46080,
                            "movieName": "密阳",
                            "movieNameEn": "Secret Sunshine",
                            "director": "李沧东",
                            "actors": "全度妍",
                            "releaseDate": "2007年5月24日",
                            "releaseLocation": "韩国",
                            "score": "7.4",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/034007.94889821_o.jpg",
                            "award": "最佳女演员奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14963,
                        "listId": 300518,
                        "ordinal": 12,
                        "rank": 12,
                        "itemId": "113564",
                        "itemType": 1,
                        "title": "和声/Harmony(2010)",
                        "coverImg": "http://img31.mtime.cn/mt/2016/09/01/173241.48096523_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 113564,
                            "movieName": "和声",
                            "movieNameEn": "Harmony",
                            "director": "姜泰奎",
                            "actors": "金允珍",
                            "releaseDate": "2010年1月28日",
                            "releaseLocation": "韩国",
                            "score": "7.8",
                            "img": "http://img31.mtime.cn/mt/2016/09/01/173241.48096523_o.jpg",
                            "award": "最佳女演员奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14964,
                        "listId": 300518,
                        "ordinal": 13,
                        "rank": 13,
                        "itemId": "210722",
                        "itemType": 1,
                        "title": "妈咪/Mommy(2014)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/09/30/163022.76799836_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 210722,
                            "movieName": "妈咪",
                            "movieNameEn": "Mommy",
                            "director": "泽维尔·多兰",
                            "actors": "安妮·杜尔瓦勒",
                            "releaseDate": "2014年5月22日",
                            "releaseLocation": "加拿大",
                            "score": "7.8",
                            "img": "http://img31.mtime.cn/mt/2014/09/30/163022.76799836_o.jpg",
                            "award": "评审团奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14965,
                        "listId": 300518,
                        "ordinal": 14,
                        "rank": 14,
                        "itemId": "214794",
                        "itemType": 1,
                        "title": "房间/Room(2016)",
                        "coverImg": "http://img31.mtime.cn/mt/2015/11/09/164817.23668912_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 214794,
                            "movieName": "房间",
                            "movieNameEn": "Room",
                            "director": "兰纳德·阿伯拉罕森",
                            "actors": "布丽·拉尔森",
                            "releaseDate": "2016年1月15日",
                            "releaseLocation": "爱尔兰",
                            "score": "7.9",
                            "img": "http://img31.mtime.cn/mt/2015/11/09/164817.23668912_o.jpg",
                            "award": "最佳故事片奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14966,
                        "listId": 300518,
                        "ordinal": 15,
                        "rank": 15,
                        "itemId": "212043",
                        "itemType": 1,
                        "title": "麦兜我和我妈妈/McDull · Me & My Mum(2019)",
                        "coverImg": "http://img5.mtime.cn/mt/2019/03/21/103134.90185940_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 212043,
                            "movieName": "麦兜我和我妈妈",
                            "movieNameEn": "McDull · Me & My Mum",
                            "director": "谢立文",
                            "actors": "吴君如",
                            "releaseDate": "2019年4月5日",
                            "releaseLocation": "中国",
                            "score": "7.6",
                            "img": "http://img5.mtime.cn/mt/2019/03/21/103134.90185940_o.jpg",
                            "award": "最佳动画长片",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14967,
                        "listId": 300518,
                        "ordinal": 16,
                        "rank": 16,
                        "itemId": "116831",
                        "itemType": 1,
                        "title": "我们需要谈谈凯文/We Need to Talk About Kevin(2011)",
                        "coverImg": "http://img5.mtime.cn/img2x/mt/2011/08/11/104044.77771441_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 116831,
                            "movieName": "我们需要谈谈凯文",
                            "movieNameEn": "We Need to Talk About Kevin",
                            "director": "琳恩·拉姆塞",
                            "actors": "蒂尔达·斯文顿",
                            "releaseDate": "2011年10月21日",
                            "releaseLocation": "英国",
                            "score": "7.7",
                            "img": "http://img5.mtime.cn/img2x/mt/2011/08/11/104044.77771441_o.jpg",
                            "award": "金棕榈奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14968,
                        "listId": 300518,
                        "ordinal": 17,
                        "rank": 17,
                        "itemId": "51899",
                        "itemType": 1,
                        "title": "意/The Home Song Stories(2007)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/040212.31546040_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 51899,
                            "movieName": "意",
                            "movieNameEn": "The Home Song Stories",
                            "director": "",
                            "actors": "陈冲",
                            "releaseDate": "2007年8月23日",
                            "releaseLocation": "澳大利亚",
                            "score": "7.7",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/040212.31546040_o.jpg",
                            "award": "最佳女主角奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14969,
                        "listId": 300518,
                        "ordinal": 18,
                        "rank": 18,
                        "itemId": "108191",
                        "itemType": 1,
                        "title": "结婚礼服/Wedding Dress(2010)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/074023.98596360_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 108191,
                            "movieName": "结婚礼服",
                            "movieNameEn": "Wedding Dress",
                            "director": "权亨镇",
                            "actors": "宋允儿",
                            "releaseDate": "2010年1月14日",
                            "releaseLocation": "韩国",
                            "score": "7.8",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/074023.98596360_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14970,
                        "listId": 300518,
                        "ordinal": 19,
                        "rank": 19,
                        "itemId": "51100",
                        "itemType": 1,
                        "title": "东京塔/Tôkyô tawâ: Okan to boku to, tokidoki, oton(2007)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/035738.45489005_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 51100,
                            "movieName": "东京塔",
                            "movieNameEn": "Tôkyô tawâ: Okan to boku to, tokidoki, oton",
                            "director": "松冈锭司",
                            "actors": "小田切让",
                            "releaseDate": "2007年4月14日",
                            "releaseLocation": "日本",
                            "score": "7.6",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/035738.45489005_o.jpg",
                            "award": "最佳亚洲电影",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14971,
                        "listId": 300518,
                        "ordinal": 20,
                        "rank": 20,
                        "itemId": "191859",
                        "itemType": 1,
                        "title": "婴儿式/Pozitia copilului(2013)",
                        "coverImg": "http://img31.mtime.cn/mt/2013/03/05/100723.19823715_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 191859,
                            "movieName": "婴儿式",
                            "movieNameEn": "Pozitia copilului",
                            "director": "卡林·皮特·内策尔",
                            "actors": "吕明妮塔·杰尔吉乌",
                            "releaseDate": "2013年3月8日",
                            "releaseLocation": "罗马尼亚",
                            "score": "",
                            "img": "http://img31.mtime.cn/mt/2013/03/05/100723.19823715_o.jpg",
                            "award": "金熊奖(竞赛单元)",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14972,
                        "listId": 300518,
                        "ordinal": 21,
                        "rank": 21,
                        "itemId": "16942",
                        "itemType": 1,
                        "title": "清洁/Clean(2004)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/23/000727.92138736_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 16942,
                            "movieName": "清洁",
                            "movieNameEn": "Clean",
                            "director": "奥利维耶·阿萨亚斯",
                            "actors": "张曼玉",
                            "releaseDate": "2004年9月1日",
                            "releaseLocation": "法国",
                            "score": "7.2",
                            "img": "http://img31.mtime.cn/mt/2014/02/23/000727.92138736_o.jpg",
                            "award": "最佳女演员奖",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14973,
                        "listId": 300518,
                        "ordinal": 22,
                        "rank": 22,
                        "itemId": "11116",
                        "itemType": 1,
                        "title": "辣妈辣妹/Freaky Friday(2003)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/22/225055.24843082_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 11116,
                            "movieName": "辣妈辣妹",
                            "movieNameEn": "Freaky Friday",
                            "director": "马克·沃特斯",
                            "actors": "杰米·李·柯蒂斯",
                            "releaseDate": "2003年8月4日",
                            "releaseLocation": "美国",
                            "score": "7.3",
                            "img": "http://img31.mtime.cn/mt/2014/02/22/225055.24843082_o.jpg",
                            "award": "音乐喜剧类最佳女主角",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14974,
                        "listId": 300518,
                        "ordinal": 23,
                        "rank": 23,
                        "itemId": "219775",
                        "itemType": 1,
                        "title": "如果和母亲一起生活/Haha to kuraseba(2015)",
                        "coverImg": "http://img31.mtime.cn/mt/2015/12/15/102627.96698906_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 219775,
                            "movieName": "如果和母亲一起生活",
                            "movieNameEn": "Haha to kuraseba",
                            "director": "山田洋次",
                            "actors": "吉永小百合",
                            "releaseDate": "2015年12月12日",
                            "releaseLocation": "日本",
                            "score": "",
                            "img": "http://img31.mtime.cn/mt/2015/12/15/102627.96698906_o.jpg",
                            "award": "最佳影片",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14975,
                        "listId": 300518,
                        "ordinal": 24,
                        "rank": 24,
                        "itemId": "253008",
                        "itemType": 1,
                        "title": "一个母亲的复仇/Mom(2019)",
                        "coverImg": "http://img5.mtime.cn/mt/2019/04/12/140947.89968390_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 253008,
                            "movieName": "一个母亲的复仇",
                            "movieNameEn": "Mom",
                            "director": "拉维·德耶瓦尔",
                            "actors": "希里黛玉",
                            "releaseDate": "2019年5月10日",
                            "releaseLocation": "印度",
                            "score": "7.1",
                            "img": "http://img5.mtime.cn/mt/2019/04/12/140947.89968390_o.jpg",
                            "award": "",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    },
                    {
                        "id": 14976,
                        "listId": 300518,
                        "ordinal": 25,
                        "rank": 25,
                        "itemId": "11507",
                        "itemType": 1,
                        "title": "漂亮妈妈/Breaking the Silence(2000)",
                        "coverImg": "http://img31.mtime.cn/mt/2014/02/22/225549.78784344_o.jpg",
                        "description": "暂无评语",
                        "movieInfo": {
                            "movieId": 11507,
                            "movieName": "漂亮妈妈",
                            "movieNameEn": "Breaking the Silence",
                            "director": "孙周",
                            "actors": "巩俐",
                            "releaseDate": "2000年4月28日",
                            "releaseLocation": "中国",
                            "score": "7.0",
                            "img": "http://img31.mtime.cn/mt/2014/02/22/225549.78784344_o.jpg",
                            "award": "最佳故事片",
                            "playState": 0,
                            "currentUserWantSee": false
                        },
                        "personInfo": null
                    }
                ],
                "itemsTotalCount": 25
            }
        ],
        "totalCount": 119
    },
    "msg": "",
    "requestId": "6409a0832112ef3850d41a60ff64f814"
}